#!/usr/bin/env zsh
##
## aliasrc by Andy3153
## created 26/10/20 ~ 14:42:12
##
## This is a secondary Zsh configuration file responsible for configuring aliases.

# Prefer doas instead of sudo if available
if [ ! -x $(which doas) ]
then
  alias doas="sudo"
fi

alias\
      clear="clear && $_scripts/ddate.sh"\
     \
      p="doas paclabel"\
      P="paru"\
     \
      f="doas flatpak"\
      fI="doas flatpak install"\
      fU="doas flatpak uninstall"\
      fS="flatpak search"\
      fL="flatpak list"\
     \
      update="paru -Syu ; doas flatpak update"\
     \
      a="doas apt"\
      ai="doas apt install"\
      ar="doas apt remove"\
      aar="doas apt autoremove"\
      ac="doas apt clean"\
      aac="doas apt autoclean"\
      aupg="doas apt update && doas apt upgrade"\
      A="doas tap"\
      Ai="doas tap install"\
      Ar="doas tap remove"\
      Aar="doas tap autoremove"\
      Ac="doas tap clean"\
      Aac="doas tap autoclean"\
      Aupg="doas tap update && doas tap upgrade"\
     \
      lss="ls -alh"\
      cd..="cd .."\
      :q="exit"\
      :Q="exit"\
      vi="nvim"\
      vim="nvim"\
      svim="doas $EDITOR"\
      dvim="svim"\
      doas="doas "\
      S="doas systemctl"\
      r="source ranger"\
      R="/usr/bin/ranger"\
      moar="moar -wrap"\
     \
      clipboard="xclip -selection clipboard"\
      catt="less -FX"\
      windowpid="xprop _NET_WM_PID"\
      xorwayland="loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type --value"\
      rpi_temp="head -n 1 /sys/class/thermal/thermal_zone0/temp | xargs -I{} awk 'BEGIN {printf \"%.2f\n\", {}/1000}'"\
     \
      YM="yt-dlp -x --audio-format mp3 --prefer-ffmpeg"\
     \
      g="git"\
      gc="git clone"\
      gs="git status"\
      gS="git stash"\
      gd="git diff"\
      gdt="git difftool"\
      gp="git pull"\
      gA="git add"\
      gA.="git add ."\
      gC="git commit"\
      gP="git push"\
     \
      d="docker"\
      db="docker build"\
      di="docker image"\
      dv="docker volume"\
      dn="docker network"\
      dex="docker exec"\
      dc="docker-compose"\
     \
      cfz="$EDITOR $ZDOTDIR/zshrc"\
      cfze="$EDITOR $HOME/.zshenv"\
      cfza="$EDITOR $ZDOTDIR/aliasrc"\
      cfzc="$EDITOR $ZDOTDIR/colorrc"\
      cfzk="$EDITOR $ZDOTDIR/keysrc"\
      cfzt="$EDITOR $ZDOTDIR/themerc"\
     \
      cfv="$EDITOR $XDG_CONFIG_HOME/nvim/init.vim"\
      cfvp="$EDITOR $XDG_CONFIG_HOME/nvim/plugins.vim"\
      cfr="$EDITOR $HOME/.config/ranger/rc.conf"\
      cfstab="doas $EDITOR /etc/fstab"\
     \
      labels="doas $EDITOR /etc/paclabel/labels"\
      flabels="doas $EDITOR /etc/paclabel/flatpak-labels"\
     \
      cddesk="cd $XDG_DESKTOP_DIR"\
      cddoc="cd $XDG_DOCUMENTS_DIR"\
      cddown="cd $XDG_DOWNLOAD_DIR"\
      cdmusic="cd $XDG_MUSIC_DIR"\
      cdpic="cd $XDG_PICTURES_DIR"\
      cdvid="cd $XDG_VIDEOS_DIR"\
      cdetc="cd $HOME/etc"\
      cdgame="cd $HOME/games"\
      cdsrc="cd $HOME/src"\
      cdtorr="cd $HOME/torrents"\
      cdvm="cd $HOME/vms"\
      cdzsh="cd $HOME/src/sh/andy3153-zshrc/"\
      cdnvim="cd $HOME/src/nvim/andy3153-init.lua/"\
      cdhypr="cd $HOME/src/hyprland/hyprland-rice/"\
      cdhyprc="cd $HOME/src/hyprland/hyprland-rice/dotconfig"\
      cdhyprl="cd $HOME/src/hyprland/hyprland-rice/dotlocal"\
      cdnix="cd $HOME/src/nixos/nixos-rice/"\
      cdnixc="cd $HOME/src/nixos/nixos-rice/etc/nixos"\
      cdnixh="cd $HOME/src/nixos/nixos-rice/home/andy3153/.config/home-manager/"\
     \
      thispc="echo && neofetch | lolcat -t"\
      parrotgif="curl parrot.live"\
      weather="curl wttr.in"\
      ipinfo="curl ipinfo.io"\ \
      rldzsh="zsh ; exit"

function ssht()
{
  /usr/bin/ssh -t "$@" "tmux attach || tmux new"
}

function run_game()
{
  suspend_compositing.sh suspend & gamemoderun $@ ; suspend_compositing.sh resume
}

## End of file.
