#!/usr/bin/env zsh
##
## aliasrc by Andy3153
## created 26/10/20 ~ 14:42:12
##
## This is a secondary Zsh configuration file responsible for configuring aliases. 

alias\
      clear="clear && $_scripts/ddate.sh"\
     \
      p="sudo pacman"\
      y="yay --sudoloop"\
      P="paru --sudoloop"\
     \
      lss="ls -alh"\
      cd..="cd .."\
      :q="exit"\
      :Q="exit"\
      755="chmod 755"\
      vi="nvim"\
      vim="nvim"\
      s="sudo"\
      svim="sudo nvim"\
      S="sudo systemctl"\
      d="docker"\
      r="source ranger"\
      R="/usr/bin/ranger"\
      catt="less -FX"\
      windowpid="xprop _NET_WM_PID"\
     \
      YM="youtube-dl -x --audio-format mp3 --prefer-ffmpeg"\
     \
      g="git"\
      gs="git status"\
      gc="git clone"\
      gp="git pull"\
      gA="git add"\
      gA.="git add ."\
      gC="git commit"\
      gP="git push"\
     \
      cfz="$EDITOR $ZDOTDIR/zshrc"\
      cfze="$EDITOR $HOME/.zshenv"\
      cfza="$EDITOR $ZDOTDIR/aliasrc"\
      cfzc="$EDITOR $ZDOTDIR/colorrc"\
      cfzk="$EDITOR $ZDOTDIR/keysrc"\
      cfzt="$EDITOR $ZDOTDIR/themerc"\
     \
      cfv="$EDITOR $XDG_CONFIG_HOME/nvim/init.vim"\
      cfvp="$EDITOR $XDG_CONFIG_HOME/nvim/plugins.vim"\
      cfr="$EDITOR $HOME/.config/ranger/rc.conf"\
      cfstab="sudo $EDITOR /etc/fstab"\
     \
      cddesk="cd $XDG_DESKTOP_DIR"\
      cddoc="cd $XDG_DOCUMENTS_DIR"\
      cddown="cd $XDG_DOWNLOAD_DIR"\
      cdmusic="cd $XDG_MUSIC_DIR"\
      cdpic="cd $XDG_PICTURES_DIR"\
      cdvid="cd $XDG_VIDEOS_DIR"\
      cdetc="cd $HOME/etc"\
      cdgame="cd $HOME/games"\
      cdsrc="cd $HOME/src"\
      cdtorr="cd $HOME/torrents"\
      cdvm="cd $HOME/vms"\
      cdzsh="cd $HOME/src/sh/andy3153-zshrc/"\
      cdnvim="cd $HOME/src/sh/andy3153-zshrc/etc/nvim"\
     \
      thispc="echo && neofetch | lolcat -t"\
      parrotgif="curl parrot.live"\
      weather="curl wttr.in"\
      ipinfo="curl ipinfo.io"\ \
      rldzsh="zsh ; exit"


## End of file.
