#!/usr/bin/env zsh
##
## keysrc by Andy3153
## created 31/01/21 ~ 14:05:08
##
## This is a secondary Zsh configuration file responsible for configuring keybindings.
##

# Bindkey mode
  bindkey -e # -v for Vi mode; -e for Emacs mode

##
## Keyboard shortcuts
##
## Use ' ^ ' for Ctrl, ' ^[ ' for Alt
##

# Basic keys
  bindkey '^[[1;5C' forward-word      # move to next word (ctrl+left_arrow)
  bindkey '^[[1;5D' backward-word     # move to previous word (ctrl+right_arrow)
  bindkey '^[[3~'   delete-char       # delete key
  bindkey '^[[H'    beginning-of-line # home key
  bindkey '^[[F'    end-of-line       # end key

# Program shortcuts
  bindkey -s '^[c' 'clear\n'          # clear (alt+c)
  bindkey -s '^[r' 'source ranger\n'  # ranger cd (alt+r)
  bindkey -s '^[v' '$EDITOR\n'        # default editor/nvim most likely (alt+v)
  bindkey -s '^[t' 'tree\n'           # show file tree in current directory (alt+t)
