"        _                    
" __   _(_)_ __ ___  _ __ ___ 
" \ \ / / | '_ ` _ \| '__/ __|
"  \ V /| | | | | | | | | (__ 
"   \_/ |_|_| |_| |_|_|  \___|
"                  by Andy3153
"
" My vimrc. Very basic

" Makes the shell interactive
  :set shellcmdflag=-ic

" Disables native insert status
  set noshowmode

" Enables syntax highlighting
  :syntax on

" Shows line numbers
  " Relative line numbering
    ":set rnu
  
  " Normal line numbering
    :set nu

" Enables mouse support
  :set mouse=a

" Makes mouse scrolling better
  :map <xCSI>[62~ <MouseDown>

" Enable spellchecking
  ":set spell

" Comes in handy when you accidentally type :W instead of :w
  cnoreabbrev <expr> W ((getcmdtype() is# ':' && getcmdline() is# 'W')?('w'):('W'))

" Shortcuts
  " Editing configs
    :command CFZ :e $HOME/.zshrc
    :command CFV :e $HOME/.vim/vimrc

" Lightline
  set laststatus=2
  let g:lightline = {
      \ 'colorscheme': 'nord',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'readonly', 'filename', 'modified', 'helloworld' ] ]
      \ },
      \ 'component': {
      \   'helloworld': 'Welcome!'
      \ },
      \ }

" Nord 
  colorscheme nord

" Tab and autoindent
    filetype plugin indent on
  " show existing tab with 2 spaces width
    set tabstop=2
  " when indenting with '>', use 2 spaces width
    set shiftwidth=2
  " On pressing tab, insert 2 spaces
    set expandtab

" End of file
